version: '3.8'
services:
  dev:
    build: 
      context: .
    ports:
      - "27015:27015/udp"
      - "27015:27015/tcp"
      - "27016:27016/udp"
      - "27016:27016/tcp"
      - "27005:27005/udp"
      - "27005:27005/tcp"
    env_file:
      - ./.env
    volumes:
      - gmod_data:/home/steam/gmodds
volumes:
  gmod_data: